DO $$
DECLARE
    author_id_is_identity text;
BEGIN
    IF to_regclass('public.authors') IS NOT NULL THEN
        SELECT is_identity
        INTO author_id_is_identity
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'authors'
          AND column_name = 'id';

        IF author_id_is_identity = 'NO' THEN
            ALTER TABLE public.authors ALTER COLUMN id DROP DEFAULT;
            ALTER TABLE public.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            PERFORM setval(
                    pg_get_serial_sequence('public.authors', 'id')::regclass,
                    COALESCE((SELECT MAX(id) FROM public.authors), 0) + 1,
                    false
                );
        END IF;
    END IF;
END
$$;
