-- Anonymous PL/pgSQL block executed by Flyway migration
DO $$
DECLARE
    -- Variable to store whether the author ID column is already an identity column ('YES' or 'NO')
    author_id_is_identity text;
BEGIN
    -- Only run this logic if the 'authors' table actually exists in the public schema
    IF to_regclass('public.authors') IS NOT NULL THEN
        -- Check the metadata in information_schema to see if 'id' is an identity column
        SELECT is_identity
        INTO author_id_is_identity
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'authors'
          AND column_name = 'id';

        -- If the 'id' column is not yet an identity column, convert it
        IF author_id_is_identity = 'NO' THEN
            -- Drop existing default value (e.g. standard serial sequence default)
            ALTER TABLE public.authors ALTER COLUMN id DROP DEFAULT;
            -- Convert the column to a modern PostgreSQL identity column
            ALTER TABLE public.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            -- Reset the underlying sequence to start after the current maximum ID to prevent key collisions
            PERFORM setval(
                    pg_get_serial_sequence('public.authors', 'id')::regclass,
                    COALESCE((SELECT MAX(id) FROM public.authors), 0) + 1,
                    false
                );
        END IF;
    END IF;
END
$$;
